Add missing commands in the install script

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,34 +1,45 @@
 #!/bin/bash
 
-# Verify if Composer are installed
-if ! composer -V > /dev/null 2>&1; then
+# Verify if Composer is installed
+if ! composer --version > /dev/null 2>&1; then
     echo 'Composer is required to run the script.';
     exit 1;
 fi
 
-# Verify if WP-CLI are installed
-if ! wp cli version > /dev/null 2>&1; then
-    echo 'WP-CLI is required to run the script.';
+# Verify if grunt-cli is installed
+if ! grunt --version > /dev/null 2>&1; then
+    echo 'grunt-cli is required to run the script.';
     exit 1;
 fi
+
+# Verify if Bower is installed
+if ! bower --version > /dev/null 2>&1; then
+    echo 'Bower is required to run the script.';
+    exit 1;
+fi
+
+# Install packages defined by composer.json file
+composer install
+
+WP_CLI='vendor/bin/wp'
 
 # Verify if the WordPress is installed, if not download and create the
 # wp-config.php
 if [ ! -f public/wp-load.php ]; then
     echo 'Downloading WordPress'
-    wp core download
+    $WP_CLI core download
 fi
 
 # Create the wp-config.php file, if not exists
 if [ ! -f public/wp-config.php ]; then
     echo 'Configuring WordPress'
-    wp core config
+    $WP_CLI core config
 fi
 
 # Install the WordPress if it isn't
-if ! wp core is-installed 2> /dev/null; then
-    wp db reset --yes 2> /dev/null || wp db create
-    wp core install
+if ! $WP_CLI core is-installed 2> /dev/null; then
+    $WP_CLI db reset --yes 2> /dev/null || $WP_CLI db create
+    $WP_CLI core install
 fi
 
 # Install extra plugins
@@ -36,8 +47,8 @@ plugins=extra/plugins/*.zip
 if [ $(ls -la ${plugins} 2> /dev/null | wc -l) -gt 0 ]; then # verify if has packages inner the directory
     for plugin in $plugins
     do
-        if ! wp plugin is-installed $(basename $plugin .zip); then
-            wp plugin install $plugin
+        if ! $WP_CLI plugin is-installed $(basename $plugin .zip); then
+            $WP_CLI plugin install $plugin
         fi
     done
 fi
@@ -47,38 +58,39 @@ themes=extra/themes/*.zip
 if [ $(ls -la ${themes} 2> /dev/null | wc -l) -gt 0 ]; then # verify if has packages inner the directory
     for theme in $themes
     do
-        if ! wp theme is-installed $(basename $theme .zip); then
-            wp theme install $theme
+        if ! $WP_CLI theme is-installed $(basename $theme .zip); then
+            $WP_CLI theme install $theme
         fi
     done
 fi
 
-# Install WPackagist plugins and themes
-composer install
-
 # Activate all plugins
-wp plugin activate --all
+$WP_CLI plugin activate --all
 
 # Remove menu items before import
-wp post delete $(wp post list --post_type='nav_menu_item' --format=ids) 2> /dev/null
+$WP_CLI post delete $($WP_CLI post list --post_type='nav_menu_item' --format=ids) 2> /dev/null
 
 # Import data
 datafiles=extra/data/*.xml
 if [ $(ls -la ${datafiles} 2> /dev/null | wc -l) -gt 0 ]; then # verify if has packages inner the directory
-    if ! wp plugin is-installed wordpress-importer; then
-        wp plugin install wordpress-importer
+    if ! $WP_CLI plugin is-installed wordpress-importer; then
+        $WP_CLI plugin install wordpress-importer
     fi
 
-    wp plugin activate wordpress-importer
+    $WP_CLI plugin activate wordpress-importer
 
     for data in $datafiles
     do
-        wp import $data --authors=create
+        $WP_CLI import $data --authors=create
     done
 fi
 
 # Update language
-wp core language update
+$WP_CLI core language update
+
+# Install NPM and Bower dependencies
+npm install
+bower install
 
 # Build the theme
 grunt
